import {Link, useParams} from "react-router-dom"

const Fizzz = () => {
    const params = useParams()
    return(<>
        <Link to='/' ><h3>Bosh saxifaga qaytish</h3></Link>
        <Link to='/fiz' ><h3>Qaytish</h3></Link><br/>
        <h1>{params.fizzz}</h1><br/>
        <img src="https://soyuzmash.ru/upload/iblock/ac4/ac49bf3af819c461500677ab18d7a934.jpeg" alt="" />
        <img src="https://naukatehnika.com/assets/cache_image/files/journal/nauka/19.02.22_velichajshaya-zagadka-fiziki/10_283x185_c8b.webp" alt="" />
        <img src="https://st4.depositphotos.com/2673929/21620/i/450/depositphotos_216201272-stock-photo-glowing-gold-and-blue-atom.jpg" alt="" />
        <p>
                        Beruniy Yerning oʻz oʻqi atrofida aylanishini oʻzi yasagan asboblar yordamida isbotladi va Yer radiusi 6490 km ga yaqin ekanligini aniqladi. U dunyoning moddiyligi, harakatning turlari, atomning boʻlinishi, atomdan keyingi zarralarning oʻzaro taʼsir kuchlari, solishtirma ogʻirlikni aniqlash usullari, jism inersiyasi, boʻshliq, atmosfera bosimi, suyuqliklar gidrostatikasi, qor, yomgʻir va doʻlning paydo boʻlish sabablari, energiya aylanishi, jismlarning elektrlanishi, dengiz hamda ummon suvlarining koʻtarilishi va pasayish sabablari, yorugʻlikning korpuskulyar hamda toʻlqin xossasi, tovush va yorugʻlik tezligi, yorugʻlikning qaytishi hamda sinishining sabablari, dispersiya hodisasi, Yer va boshqa sayyoralarning Quyosh atrofidagi harakatlari ellips shakliga yaqinligi, fazoviy jismlarning vaznsizligi toʻgʻrisida fikrlar yuritdi. Abu Nasr al-Forobiyning tovush tezligi, tovushning toʻlqin tabiati, tovush chastotasi, tovush toʻlqinining uzunligi haqidagi fikrlari va ularga asoslanib yaratilgan musiqa notasi hamda optikaga oid koʻpgina ishlari fizika fanining rivojlanishiga qoʻshilgan katta hissa boʻldi. Ibn Sino harakatning nisbiyligi, inersiya, kuch, massa va tezlanish orasidagi bogʻlanish, aylanma harakat, markazga intilma kuch, chizikli tezlik, boʻshliq va atmosfera bosimi, konveksiya, issiqlikning tabiati, issiqlik uzatilishining turlari, yashin va yashinning turlari, momaqaldiroq hodisasi, tovush va yorugʻlik tezligi, yorugʻlik dispersiyasi, linza, atom tuzil ishi va boshqa mavzularga tegishli mulohazalarining aksariyati hozirgi zamon tushunchalariga juda moye keladi.

                Hakim Termiziy dunyoviy fanlarning ungacha boʻlgan yutuqlarini qomusiy olim sifatida oʻrgandi, jumladan, tabiat hodisalari va jarayonlarini tahlil etuvchi „Solnoma“, „Haftanoma“ kabi asarlari maʼlum. Mirzo Ulugʻbek XV asrda jahonda yagona rasadxona qurdi. Uning „Ziji Koʻragoniy“ asarida astronomiyaning nazariy asoslari yoritdi va 1018 ta yulduzning joylashish koordinatalarini juda katta aniqlikda berdi. Uning qiymatlari hozirgi qiymatlarga juda yaqin.

                Fizik hodisalarni tushuntirishda Oʻrta Osiyolik olimlarning mulohazalari qadimgi anʼanalar taʼsirida rivojlangan boʻlsada, ular matematik usullarni keng joriy etib, tajribalardan foydalanib, fanga katta hissa qoʻshdilar.

                Klassik fizikaning rivojlanishi. XVII asrga kelib G. Galiley mexanik harakatni tajriba yoʻli bilan oʻrganib, harakatni matematik formulalar asosida ifodalash zarurligini aniqladi va bu fizika fanining keskin rivojiga turtki boʻldi. U jismlarning oʻzaro taʼsiri natijasida tezlik oʻzgarib, tezlanish hosil boʻlishini, taʼsir boʻlmaganda harakat holatining oʻzgarmasligi, yaʼni tezlanishning nolga tengligini yoki tezlikning oʻzgarmasdan saqlanishini qayd etib, Aristotelning shu masalaga qarashli fikrini, yaʼni taʼsir natijasida tezlik hosil boʻlishini inkor etadi. Keyinchalik Galiley aniqlagan qonun inersiya qonuni yoki Nyutonning mexanikaga oid birinchi qonuni degan nom oldi. 1600-yilda U. Gilbert elektr va magnit hodisalarni oʻrganish bilan shuhrat qozondi hamda Yer tirik magnit ekanligini isbotladi. U kompas magnit milining burilishini Yerning katta magnitga oʻxshashi orqali tushuntirdi, magnetizm va elektrning oʻzaro bogʻlanishini tekshirdi. Galiley mexanikadagi nisbiylik prinsipini ochdi va erkin tushayotgan jism tezlanishi uning tezligi va massasiga bogʻliq emasligini isbotladi. E.Torrichelli yuqoridagi prinsipdan foydalanib, atmosfera bosimining mavjudligini aniqladi va birinchi barometrni yaratdi. R. Boyl va E. Mariott gazlarning elastikligini aniqladilar hamda gazlar uchun birinchi qonun - Boyl-Mariott qonunini yaratdilar. Gollandiyalik astronom va matematik V. Snellius (Snell) bilan R. Dekart yorugʻlik nurining sinish qonunini ochdilar.

                XVII asr Fizikasining eng katta yutuqlaridan biri klassik mexanikaning yaratilishi boʻldi. I. Nyuton 1687-yilda Galiley va oʻz zamondoshlarining gʻoyalarini umumlashtirib, klassik mexanikaning asosiy qonunlarini taʼriflab berdi. Nyuton tomonidan jismlar holati tushunchasining kiritilishi barcha fizik royalar uchun muhim boʻldi, jismlar tizimining holatini mexanikada ularning koordinatalari va impulslari orqali toʻla aniqlash imkoniyati yaratildi. Agar jismning boshlangʻich vaqtdagi holati hamda harakat davomida unga taʼsir etuvchi kuchlarning tabiati maʼlum boʻlsa, Nyuton qonunlariga asoslangan holda shu jismning harakat tenglamasini tuzish mumkin. Bu harakat tenglamasidan foydalanib, ushbu jismning istalgan vaqtdagi fazodagi oʻrnini, tezlik, tezlanish va fizik kattaliklarni aniqlash mumkin boʻldi. Nyuton sayyoralar harakatlarini tushuntiruvchi Kepler qonunlari asosida butun olam tortishish qonunini ochdi va bu qonun orqali Oy, sayyoralar va kometalar harakatini isbotlab berdi. X. Poygens va G. Leybnis harakat miqdorining saqlanish qonunini taʼrifladilar.

                XVII asrning 2-yarmida fizik optika asoslari yaratila boshlandi, teleskop va boshqa optik qurilmalar yaratildi. Fizik A. Grimaldi yorugʻlik difraksiyasini, I. Nyuton esa yorugʻlik dispersiyasiik tadqiq qildi. 1676-yilda daniyalik astronom O. Ryomer yorugʻlik tezligini oʻlchadi. Shu davrdan yorugʻlikning korpuskulyar va toʻlqin nazariyalari yuzaga keldi hamda rivoj topa boshladi. I. Nyuton yorugʻlikni korpuskula (zarra)lar harakati orqali tushuntirsa, X. Gyuygens uni faraz qilinuvchi muhit — efirda tarqaladigan toʻlqinlar yordamida tushuntirdi.

                Shunday qilib, XVII asrda klassik mexanika mustahkam oʻrin egalladi, akustika, optika, elektr va magnetizm, issiqlik hodisalarini oʻrganish sohalarida katta izlanishlar boshlandi. XVIII asrga kelib tajriba va mat.dan keng foydalangan klassik mexanika va osmon mexanikasi yanada tez surʼatlar bilan rivojlandi. Yer va Osmon hodisalarini mexanika qonunlari orqali tushuntirish asosiy maqsad hamda bosh taʼlimot hisoblanar edi. Hatto, oʻrganilayotgan fizik hodisani mexanika qonunlari orqali tushuntirish mumkin boʻlmasa, tanlangan tushuntirish yoʻli toʻliq emas yoki notoʻgʻri deb yuritilar edi.

                XVIII asrda zarralar va qattiq jismlar mexanikasi bilan birga gaz hamda suyuqliklar mexanikasi rivojlandi. D. Bernulli, L. Eyler, J. Lagranj va boshqalar ideal suyuqlik gidrodinamikasiga asos soldilar. Fransuz olimi Sh. Dyufe elektrning ikki turi mavjudligini aniqladi hamda ularning oʻzaro tortilish va itarilishini koʻrsatdi. Amerikalik olim B. Franklin elektr zaryadining saqlanish qonunini aniqladi. T. Kavendish va undan mustasno Sh. Kulon qoʻzgʻalmas elektr zaryadining oʻzaro taʼsir kuchini tajribada aniqladilar hamda matematik ifodasini topib, asosiy qonun - Kulon qonunini ochdilar.

                Rus fiziklari G. Rixman, M.V. Lomonosov va amerikalik olim B. Franklin atmosferada hosil boʻladigan elektr, yashinning tabiatini tushuntirib berdilar. A. Galvani, A. Volta va keyinchalik rus fizigi hamda elektrotexnigi V. Petrovning kuzatishlari va tadqiqotlari elektrodinamikaning vujudga kelishi hamda tez surʼatlar bilan rivojlanishiga sabab boʻldi. Optika sohasida P. Buger va I. Lambert ishlari tufayli fotometriyaga asos solindi. Infraqizil (ingliz optigi V. Gershel va ingliz kimyogari U. Vollston) va ultrabinafsha (ingliz kimyogari I. Ritter) nurlar mavjudligi aniqlandi. Issiqlik hodisalari, issiqlik miqdori, issiqlik sigʻimi, issiqlik oʻtkazuvchanlik va h.k.ni oʻrganishda ham qator izlanishlar olib borildi. M. Lomonosov, R. Boyl, R. Guk, Bernullilar issiqlikning molekulyar-kinetik nazariyasiga asos soldilar.

                XIX asr boshida T. Yung va O. Frenellarning toʻlqin nazariyasi asosida yorugʻlik difraksiyasi va yorugʻlik interferensiyasi yaratildi. Yorugʻlikni koʻndalang toʻlqin sifatida elastik muhitda tarqaladi deb, Frenel singan va qaytgan yorugʻlik toʻlqinlarining intensivligini belgilovchi miqdoriy qonunni aniqladi. Fransuz fizigi E. Malyus yorugʻlikning qutblanishi hodisasini kashf etdi, yorugʻlik spektriga va difraksiyasiga tegishli izlanishlar olib bordi. Yorugʻlikning tabiati haqidagi korpuskulyar va toʻlqin nazariyalari orasidagi deyarli ikki asr davom etgan kurash toʻlqin nazariyasi foydasiga hal boʻldi.

                Italiyalik olimlar A. Galvani va A.Voltalarning elektr tokini kashf etishlari hamda dunyoda birinchi marta 1800-yilda galvanik elementning yasalishi fizika fanining rivojlanishida katta ahamiyatga ega boʻldi. 1820-yilda daniyalik fizik X. Ersted tokli oʻtkazgichning kompas mili bilan oʻzaro taʼsirda boʻlishini elektr va magnit hodisalar orasida bogʻlanish borligi bilan tushuntirdi. Shu yillarda A. Amper zaryadlangan zarralarning tartibli harakati tufayli paydo boʻluvchi elektr toki bilan barcha magnit hodisalari bogʻliq ekanligi toʻgʻrisida xulosaga keldi va tajriba asosida tokli oʻtkazgichlar orasidagi vujudga keluvchi oʻzaro taʼsir kuchini ifodalovchi qonunni ixtiro qildi (Amper qonuni). 1831-yilda M. Faradey elektromagnit induksiya hodisasini ochdi va elektromagnit maydon tushunchasi haqidagi taʼlimotni yaratdi. Metallarning elektr oʻtkazuvchanligini oʻrganish Om qonunining (1826), moddalarning issiqlik xususiyatlarini oʻrganish — issiqlik sigʻimi qonunining yaratilishiga olib keldi.

                Tabiatning barcha hodisalarini bir butun qilib bogʻlovchi energiyaning saqlanish va aylanish qonunining ochilishi tabiatshunoslikda, jumladan, fizikaning rivojlanishida katta ahamiyatga ega. XIX asr oʻrtalariga kelib tajriba orqali issiqlik miqdori bilan bajarilgan ish miqdorining oʻzaro qiyosiy tengligi isbotlandi va shu asosda issiqlik energiyaning maxsus turi ekanligi aniqlandi. Energiyaning saqlanish va aylanish qonuni issiqlik hodisalari nazariyasining asosiy qonuni boʻlib, u termodinamikaning birinchi bosh qonuni deb ataladi. Bu qonunni Yu.R. Mayer taʼriflagan, nemis fizigi G. Gelmgols aniqroq shaklga keltirgan (1874). Termodinamikaning rivojlanishida S. Karno, R. Klauzius, U. Tomson, E. Klapeyron va D.I. Mendeleyevlarning xizmatlari katta boʻldi. S. Karno issiqlikning mexanik harakatga aylanishini aniqladi, R. Klauzius, U. Tomson issiqlik nazariyasining asosiy qonuni - termodinamikaning ikkinchi bosh qonunini taʼrifladilar, R. Boyl, E. Mariott, J. Gey - Lyussak, B. Klapeyron ideal gazning holat tenglamasini aniqladilar. D.I. Mendeleyev uni barcha gazlar uchun umumlashtirdi va h.k. Termodinamika bilan birga issiqlikning molekulyar-kinetik nazariyasi rivojlanib bordi. A. Eynshteyn, polyak fizigi M. Smoluxovskiy va fransuz fizigi J. Perrenlar Broun harakati atom hamda molekulalarning issiqlik harakati ekanligini isbotlab, molekulyar-kinetik nazariya asoslari boʻlgan Broun harakatining miqdoriy nazariyasini yaratdilar. Bu esa, oʻz navbatida, statistik mexanikaning toʻla tan olinishiga olib keldi. J.K. Maksvell kiritgan ehtimollik xarakteriga ega boʻlgan statistik tushunchalar asosida gazlardagi molekulalar tezligi, erkin yugurish uzunligi, vaqt birligi ichidagi toʻqnashuvlar soni va boshqa kattaliklarning oʻrtacha qiymatlarini topishga yoʻl ochildi, uning molekulalarning oʻrtacha kinetik energiyasiga bogʻliqligi koʻrsatildi. Materiyaning kinetik nazariyasi taraqqiy etishi L. Bolsman tomonidan statistik mexanika - Bolsman statistikasi yaratilishiga olib keldi. XIX asrning 2-yarmida J.K. Maksvell elektromagnit hodisalarning elektromagnit maydon tushunchasiga asoslangan yangi nazariyasini va uni ifodalovchi tegishli tenglamalar tizimini yaratdi. U tabiatda elektromagnit toʻlqinlarning mavjudligini, ularning aniq, xususiyatlari — bosimi, difraksiyasi, interferensiyasi, tarqalish tezligi, qutblanishi va h.k. borligini aniqladi. Maksvell nazariyasining eng muhim natijasi elektromagnit toʻlqinlarning tarqalish tezligi yorugʻlik tezligiga teng boʻlgan qiymatga ega ekanligi toʻgʻrisidagi xulosa hisoblandi. Maksvell nazariyasidan yorugʻlikning elektromagnit xususiyatiga ega ekanligi kelib chiqdi. G. Gersning elektromagnit toʻlqinlarni aniqlash boʻyicha olib borgan tajribalari buni tasdiqladi. 1899-yil P. Lebedev yorugʻlikning bosimini tajriba orqali aniqladi. 1895-yilda A.S. Popov Maksvell nazariyasidan foydalanib simsiz aloqani yaratdi. Yuqoridagi va boshqa tajribalar Maksvellning elektromagnit nazariyasi toʻgʻriligiga yakun yasadi.
        </p>
    </>)
}
export default Fizzz;