import {Link, useParams} from "react-router-dom"

const SHeriyat = () => {
    const params = useParams()
    return(<>
    
    <Link to='/' ><h3>Bosh saxifaga qaytish</h3></Link>
    <Link to='/badiy' ><h3>Qaytish</h3></Link><br/><br/>
    <h1>{params.sheriyat}</h1>
    <img src="https://yt3.googleusercontent.com/ytc/AGIKgqNhhfaU7uGacX8JZ-WDNDBuOFSwPPRYACanlNqE8Q=s900-c-k-c0x00ffffff-no-rj" alt="" />
    <p>
            Sheʼriyat — sheʼriy asarlar majmui. Dastlab sheʼriyat deyilganda, umuman, badiiy adabiyot tushunilgan. Sheʼriyat badiiyatga daxldor sanalgan.

        Insoniyat tarixida faqat sheʼr shaklida yozilgan bitiklargina soʻz sanʼatiga tegishli hisoblab kelingan. Garchi qadim zamonlarda ham nasrga oid asarlar yaratilgan boʻlsada, ular nafis sanʼatga, badiiy adabiyotga tegishli emas, deb qaralgan. Sheʼrning muayyan ichki tartib asosiga qurilganligi, oddiy soʻzlashuvga oʻxshamasligi, hamma ham fikru tuygʻularini bu shakdda ifodalay olmasligi unga qandaydir sirlilik, mumtozlik maqomini beradi. Bunday qarash butun dunyoda hukmron boʻlgan. Yevropada Uygʻonish davriga kelibgina nasriy asarlar badiiy adabiyotga tegishli ekanligi tan olingan. Rossiyada 19-asr boshlarida nasriy asarlar ham badiiy adabiyot namunalari sanaladigan boʻldi. Musulmon Sharqida esa, nasrni soʻz sanʼatiga tegishli, deb hisoblamaslik 19-asr oxirlariga qadar davom etib keldi. Alisher Navoiy „Hayrat ulabror“ asarida chamanzordagi gul kabi goʻzal va tartibli sheʼr (nazm)ning tuproqqa qorishib yotgan chechak singari boʻlgan nasrdan mislsiz darajada ustun ekanligini „Nazm anga gulshanda ochilmogʻligʻi, Nasr qaro yergʻa sochilmogʻligʻi“ va „Boʻlmasa eʼjoz (moʻʼjiza) maqomida nazm, Boʻlmas edi Tengri kalomida nazm“ tarzida ifoda etadi. Shuning uchun ham oʻzbek adabiyoti tarixida Sh. ustuvor oʻrin tutadi. shahrining axborot berish vositasigina boʻlgan soʻzlashuvdan yoki fikrni tushuntirish yoʻli boʻlmish ilmiy bayondan oʻzining alohida qurilishi, nutqning odatdagi talablariga boʻysunmasligi bilan ajralib turishi, kishida hissiyot uygʻotadigan ohangga egaligi ajdodlarimizda unga nisbatan ehtiromli munosabat uygʻotgan. shahriga xos musiqiylik, tartiblilik, shartlilik uni oʻz-oʻzidan ijodga, badiiyatga daxldor qilib qoʻrsatgan. SH. tufayli inson nutqi jarangdor musiqiylik, tugallik, butunlik va uygʻunlik kasb etadi. Chunki shahrida soʻzning sehrli jozibasi, odam ruhiyatiga taʼsir koʻrsata oladigan darajadagi koʻtarinkiligi namoyon boʻlgan. Qadimda shahriga ijro etiladigan, binobarin, kishilar tomonidan bevosita idrok qilinadigan hodisa sifatida qaralgan. Minglab yillar mobaynida Sh., asosan, inson tuygʻulariga taʼsir koʻrsatish vositasi sanalgani uchun ham uning musiqiyligi, ohangdorligi va jarangdorligiga alohida eʼtibor berilgan. Sh. namunalari faqat mazmuni bilan emas, balki ifoda tarzi orqali ham oʻquvchilar va tinglovchilarni rom etgan. Bu hol Sh. namunalarining kuylaydigan darajadagi qatʼiy akustik xususiyatlarga ega boʻlishini taqozo qilgan. shahrida muayyan musiqiy zarb (ritm) va qofiya, poetik sintaksis va inversiyalar qoʻllanishi soʻzlarning harakatchanligi, ohangdorligi va yoqimliligini taʼminlaydi. Bu hol mazmun tovlanishlariga erishish borasida shahriga tuganmas imkoniyatlar beradi.
        Nasriy asarlar oʻquvchi tomonidan yolgʻiz idrok etilgani, asosan, ichda oʻqilgani uchun ham muallif hamda qahramonlar ovozini har bir kishi alohida „ichki quloq“ bilan eshitgan. SH. uchun voqea va tafsilotlar tasviri emas, balki inson ruhiyati ifodasi muhimdir. Bu borada oʻzbek Sh.i ayricha yuksak maqomda turadi. Shu bois milliy Sh. uchun voqeabandliqdan koʻra inson tuygʻulari jilvasi, chigal kechinmalarini hissiyotga taʼsir etadigan, uni titroqqa soladigan yoʻsinda ifoda etish muhimdir. Qatʼiy poetik qoliplarga amal etilgan holda sheʼriy kashfiyotlar qilish zaruriyati oʻzbek Sh.ining mukammallashuviga olib keldi. Shoir sheʼriy olamining tamomila oʻzgachaligi, muayyan sheʼrda ifodalangan poetik mazmunni boshqa asarlarda, boʻlakcha yoʻsinda berish deyarli mumkin emasligi shahrida universallikning koʻzga koʻrinmaydigan, ilgʻab boʻlmaydigan darajada kam ekanligiga sababdir. Har bir sheʼr oʻzigagina mansub qoida bilan tugʻiladi va shunga koʻra yashaydi.
        Choʻlpon qalamiga mansub quyidagi misralarda shahriga xos ayni shu xususiyatlarni koʻrish mumkin:Bir tugam sochlaring mening qoʻlimda, Gʻijimlab oʻpaymi yo tarab ochay? Sir deb saqlaganing mening qoʻynimda, Sir deb saqlayinmi yo yelga sochay? Sochilgan sochingday sochilsa siring , Anor yuzlaringni kimga tugasan? Oʻzingku ularda vafo yoʻq deding , Nimaga ularni tagʻin kutasan?Bu misralar nasriy matnga aylantirilsa, undagi sirlilik, taʼsirchanlik, mukammallik butunlay yoʻqqa chiqib, oddiy soʻzlarning unchalik ham mantiqli boʻlmagan yigʻindisiga aylanib qoladi. shahrining sehri uning mohiyatini anglash mushkulligida, mazmunning tutqich bermasligidadir.
        Shoirning oʻzigagina xos jonli ohang, faqat oʻzigagina tegishli betakror ruhiy holatning ifodalanishi shahrini yuksak darajaga koʻtaruvchi omildir. Soʻz sanʼatining alohida shakli sifatida nasrning paydo boʻlishi oʻzbek Sh.ining mohiyatini oʻzgartirib, taraqqiyotini susaytirib qoʻymagan boʻlsada, uning tabiatiga jiddiy taʼsir koʻrsatadi. Yangi oʻzbek Sh.i yanada nafislashdi, yanada turfalashdi. Sh. jamiyat va tabiatda roʻy bergan hayotiy hodisani badiiy hodisaga aylantirish vositasi hamda shaxsiy kechinmalarni, shoirning betakror va haqiqiy hislarini ifoda qilishning yoʻli sifatida shiddat bilan rivojlanmoqda. Shubhasiz, yangi oʻzbek Sh.i koʻproq lirik mohiyat kasb etayotir.
    </p>
    </>)
}
export default SHeriyat;